# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: e79236e7b0f43fe8d88d79ab45cfae92aab8f8f072034dc8d7360017d7c39508cc045deb2ebf9e069eda9f35eeed8c6497391badcf702693fbff565b52510589

test:
  secret_key_base: a97dc33cbff71025788042e61e2413800cc90fec5a586ec74856ac3f9115c538305d4570d62b980414ac8a0ac52071ee19e1244dc435384b3bc6edb39d8949c4

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
